# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1390ee0bbbef403253765d24bcbe0f91fa8cd9e7d32bf2280f61bfd33c4eacb5d1e000bce8a4cc9a1d6485786e79166e517ccac40f587321703602b68d499f68

test:
  secret_key_base: a78528a03c48364547f2937ebf6c308ca92a99091423d65e25d2a49344e4e03708649ab7354cc040da0b0636c8414ae4994a90f2ec16f8089632d02f0cd4d390

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
